name: Build

on:
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - name: npm ci and build
      run: |
        npm ci
        npm run build