name: Build

on:
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: 18.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - name: npm ci and build
      run: |
        npm ci
        npm run build